# Generated by Django 4.0.2 on 2022-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('year', models.DateField()),
                ('imdb', models.URLField()),
                ('genre', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Actor_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.ManyToManyField(related_name='actors', to='actor.Actor')),
                ('movie_name', models.ManyToManyField(related_name='movies', to='actor.Movie')),
            ],
        ),
    ]
