# Generated by Django 4.0.2 on 2022-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_rename_actor_movie_movie_actor_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.URLField(),
        ),
    ]
