# Generated by Django 4.0.2 on 2022-02-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='actor.Actor'),
        ),
        migrations.DeleteModel(
            name='Movie_Actor',
        ),
    ]
