# Generated by Django 4.0.2 on 2022-02-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0008_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(),
        ),
    ]
