# Generated by Django 4.0.2 on 2022-02-24 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0009_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 2, 24)),
        ),
    ]
