name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-tests:
    services:
      postgres:
        image: postgres
	enviroment:
	  - POSTGRES_DB = postgres
          - POSTGRES_USER = postgres 
          - POSTGRES_PASSWORD =  postgresdata/db/pg_stat_tmp/db_0.stat
        ports:
        - 5432:5432
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Requirements
      run:  pip install -r requirements.txt
       
    - name: Run Tests
      run: pytest
